_target_: pytorch_lightning.Trainer

gpus: -1 # Specify GPU by CUDA_VISIBLE_DEVICES=0 
min_epochs: 1
max_epochs: 800
log_every_n_steps: 5
precision : 16
num_sanity_val_steps : 0 # This does not work with dp, only with ddp
check_val_every_n_epoch : 1
benchmark: True
overfit_batches: False

